#include </com/sun/star/uno/XInterface.idl>

module com { module loc { module crypto { module getinfo {

    interface LOC
    {
      any runCommand( [in] string a);
      any getCryptoBridge( [in] string a, [in] any b );
      any getPoloniex( [in] string a, [in] any b );
      any ccxt( [in] string a, [in] any b, [in] any c );
    };

}; }; }; };
