#include </com/sun/star/uno/XInterface.idl>

module com { module loc { module crypto { module getinfo {

    interface LOC
    {
      any runCommand( [in] string a);
      any getSouthXchange( [in] string a, [in] any b );
      any getPoloniex( [in] string a, [in] any b );
      any ccxt( [in] string a, [in] any b, [in] any c );
      any xrs( [in] string a, [in] any b);
      any xcs( [in] string a, [in] any b);
    };

}; }; }; };
